version: "3.8"

services:
  # custom image
  app:
    build:
      args:
        user: hugo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hugo_chiesse/laravel_app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: always
    depends_on:
      - redis
      - queue
    networks:
      - docker-laravel

  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8989:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  # redis
  redis:
    image: redis:latest
    networks:
      - docker-laravel

  #queue
  queue:
    build:
      args:
        user: hugo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - docker-laravel

  mysql:
    image: mysql:5.7.39
    restart: always
    ports:
      - 3389:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge
